blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='bloglist'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='blogdetail'),
    # path('upload_image/', views.upload_image, name='upload_image'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('tinymce/', include('tinymce.urls')),
    path('blogs/', include("blog.urls")),
    path('shop/', include("shop.urls")),
    path('gallery/', include("gallery.urls")),
    path('training/', include("training.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index_view, name='home'),
    path('agri-drone', views.agri_view, name='agri-detail'),
    path('about', views.about_view, name='about'),
    path('contact', views.contact_view, name='contact'),
    path('career', views.career_view, name='career'),
    path('mapping', views.mapping_view, name='mapping'),
    path('thrustbench', views.tb_view, name='tb'),
    path('uav-data-processing', views.uav_data_processing_view, name='uav-data-processing'),
    path('subscribe', views.subscribe_newsletter, name='subscribe_newsletter'),
    path('whatsapp-redirect', views.whatsapp_redirect, name='whatsapp-redirect'),
    path('lang-select', views.set_language, name='set-language'),
    path('upcoming', views.upcoming_view, name='upcoming-page'),
]

core/models.py
from django.db import models

# Create your models here.
class Subscriber(models.Model):
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.email

core/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        label='Name',
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Your Name'})
        
    )
    email = forms.EmailField(
        label='Email',
        max_length=200,
        widget=forms.TextInput(attrs={'placeholder': 'Your Email'})
    )
    message = forms.CharField(
        label='Message',
        widget=forms.Textarea(attrs={'placeholder': 'Your Message'})
    )


class SubscriberForm(forms.Form):
    email = forms.EmailField()


class CareerForm(forms.Form):
    name = forms.CharField(
        label='Name',
        required=True,
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Enter Your Name...'})
        
    )
    email = forms.EmailField(
        label='Email',
        required=True,
        max_length=200,
        widget=forms.TextInput(attrs={'placeholder': 'Enter Your Email...'})
    )
    position = forms.CharField(
        label='Position', 
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Applying For Position...'})
    )
    message = forms.CharField(
        label='Message',
        widget=forms.Textarea(attrs={'placeholder': 'Your Message'})
    )
    resume = forms.FileField(
        required=True,
        label='Resume',
        # widget=forms.ClearableFileInput(attrs={'multiple': False})
        )
    
    def clean_resume(self):
        resume = self.cleaned_data.get('resume')
        if resume:
            if not resume.name.endswith('.pdf'):
                raise forms.ValidationError("Only PDF files are allowed.")
            if resume.size > 2 * 1024 * 1024:  # 2 MB limit
                raise forms.ValidationError("The file size should not exceed 2 MB.")
        return resume

core/views.py
import os
from django.shortcuts import redirect, render
from django.utils import translation
from django.core.mail import send_mail, EmailMessage
from .pdf_utils import generate_pdf
from django.http import HttpResponseRedirect, JsonResponse
from .models import Subscriber
from blog.models import Post
from .forms import ContactForm, SubscriberForm, CareerForm
from django.views.decorators.csrf import csrf_exempt
from django.conf import settings
import urllib.parse


def index_view(request):
    """
    Renders the index page with the latest 3 blog posts.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered index page.
    """
    # Get the latest 3 blog posts
    latest_blogs = Post.objects.order_by('-created_at')[:3]

    # Render the index page with the latest blog posts
    return render(request, "core/index.html", context={'latest_blogs': latest_blogs})


def agri_view(request):

    if request.method == 'POST':
        # Create a form instance with the POST data
        form = ContactForm(request.POST)

        # Validate the form data
        if form.is_valid():
            # Get the cleaned form data
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            # Send email to the admin
            try:
                send_mail(
                    'Test Mail',
                    f'Name: {name}\nEmail: {email}\n\nMessage:\n{message}',
                    settings.DEFAULT_FROM_EMAIL,  # Or use email
                    ['admin@droneanatomy.com'],
                    fail_silently=True,
                )

                # Check if the request is an AJAX request
                if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                    return JsonResponse({'success': True, 'message': 'Message sent successfully!'})
                # Ensure the name here matches your URL pattern name

            # Handle exceptions while sending the email
            except Exception as e:
                error_message = f'Error: {e}'

                # Check if the request is an AJAX request
                if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                    return JsonResponse({'success': False, 'error': error_message})
                else:
                    # Render the contact page with the form and error message
                    return render(request, 'core/agri-drone.html', {'form': form, 'error': error_message})

        else:
            # Get the form errors as JSON
            errors = form.errors.as_json()

            # Check if the request is an AJAX request
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                # Return JSON response with the form errors
                return JsonResponse({'success': False, 'errors': errors})
            else:
                # Render the contact page with the form and errors
                return render(request, 'core/agri-drone.html', {'form': form, 'errors': form.errors})

    else:
        # Create an empty form instance
        form = ContactForm()

        # Get the success query parameter from the request
        success = request.GET.get('success')

        # Render the contact page with the form and success message (if any)
        return render(request, 'core/agri-drone.html', {'form': form, 'success': success})


def tb_view(request):

    return render(request, 'core/tb.html', {})


def uav_data_processing_view(request):

    return render(request, 'core/uav-data-processing.html', context={})


def mapping_view(request):

    return render(request, 'core/mapping.html', context={})


def about_view(request):
    """
    Renders the about page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered about page.
    """
    # Render the about page
    return render(request, "core/about.html", context={})


def career_view(request):
    """
    Renders the career page.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered career page.
    """
    if request.method == 'POST':
        # Create a form instance with the POST data
        form = CareerForm(request.POST, files=request.FILES)

        # Validate the form data
        if form.is_valid():
            # Get the cleaned form data
            name = request.POST.get('name')
            email = request.POST.get('email')
            position = request.POST.get('position')
            message = request.POST.get('message')
            resume = form.cleaned_data.get('resume')
            
            # Generate PDF
            pdf_path = generate_pdf(name, email, message)

            # Send email to the admin
            try:
                send_career_form_email(name, email, position, message, pdf_path, resume)
        
        # Remove the temporary PDF file
                os.remove(pdf_path)

                # Check if the request is an AJAX request
                if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                    return JsonResponse({'success': True, 'message': 'Message sent successfully!'})
                # Ensure the name here matches your URL pattern name

            # Handle exceptions while sending the email
            except Exception as e:
                error_message = f'Error: {e}'

                # Check if the request is an AJAX request
                if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                    return JsonResponse({'success': False, 'error': error_message})
                else:
                    # Render the contact page with the form and error message
                    return render(request, 'core/career.html', {'form': form, 'error': error_message})

        else:
            # Get the form errors as JSON
            errors = form.errors.as_json()

            # Check if the request is an AJAX request
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                # Return JSON response with the form errors
                return JsonResponse({'success': False, 'errors': errors})
            else:
                # Render the contact page with the form and errors
                return render(request, 'core/career.html', {'form': form, 'errors': form.errors})

    else:
        # Create an empty form instance
        form = CareerForm()

        # Get the success query parameter from the request
        success = request.GET.get('success')

        # Render the contact page with the form and success message (if any)
        return render(request, 'core/career.html', {'form': form, 'success': success})

# Add comments and docstrings to the code for better readability and understanding


def contact_view(request):
    """
    Handles the contact form submission and sends an email to the admin.

    Args:
        request (HttpRequest): The request object.

    Returns:
        HttpResponse: The rendered contact page or JSON response.
    """
    # Check if the request method is POST
    if request.method == 'POST':
        # Create a form instance with the POST data
        form = ContactForm(request.POST)

        # Validate the form data
        if form.is_valid():
            # Get the cleaned form data
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            # Send email to the admin
            try:
                send_mail(
                    'Contact Form - Website',
                    f'Name: {name}\nEmail: {email}\n\nMessage:\n{message}',
                    settings.DEFAULT_FROM_EMAIL,  # Or use email
                    ['admin@droneanatomy.com'],
                    fail_silently=True,
                )

                # Check if the request is an AJAX request
                if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                    return JsonResponse({'success': True, 'message': 'Message sent successfully!'})
                # Ensure the name here matches your URL pattern name

            # Handle exceptions while sending the email
            except Exception as e:
                error_message = f'Error: {e}'

                # Check if the request is an AJAX request
                if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                    return JsonResponse({'success': False, 'error': error_message})
                else:
                    # Render the contact page with the form and error message
                    return render(request, 'core/contact.html', {'form': form, 'error': error_message})

        else:
            # Get the form errors as JSON
            errors = form.errors.as_json()

            # Check if the request is an AJAX request
            if request.headers.get('x-requested-with') == 'XMLHttpRequest':
                # Return JSON response with the form errors
                return JsonResponse({'success': False, 'errors': errors})
            else:
                # Render the contact page with the form and errors
                return render(request, 'core/contact.html', {'form': form, 'errors': form.errors})

    else:
        # Create an empty form instance
        form = ContactForm()

        # Get the success query parameter from the request
        success = request.GET.get('success')

        # Render the contact page with the form and success message (if any)
        return render(request, 'core/contact.html', {'form': form, 'success': success})
    

def upcoming_view(request):

    return render(request, "core/upcoming.html", {})


def whatsapp_redirect(request):
    """
    Redirects the user to a WhatsApp chat with a predefined phone number and message.

    Returns:

core/templates/core/counter.html
<section
  id="counter-section"
  class="w-full"
  
>
  <div data-aos="fade-in" class="container mx-auto py-20 grid grid-cols-2 xl:grid-cols-4 gap-10 text-black font-semibold w-10/12">
    <div class="container border-b-2 px-3 space-y-3">
      <h1  class="xl:text-6xl md:text-5xl text-3xl value" tar="120"><span id="project-counter" class="value" tar="16">0</span>+</h1>
      <p class="text-sm font-normal">Projects Completed</p>
      <div class=""></div>
    </div>
    <div class="container border-b-2 px-3 space-y-3">
      <h1 class="xl:text-6xl md:text-5xl text-3xl "><span id="exp-counter" class="value" tar="16">0</span>+</h1>
      <p class="text-sm font-normal">Years of Experience</p>
      <div class=""></div>
    </div>
    <div class="container border-b-2 px-3 space-y-3">
      <h1 class="xl:text-6xl md:text-5xl text-3xl "><span id="client-counter" class="value" tar="46">0</span>+</h1>
      <p class="text-sm font-normal">Clients</p>
      <div class=""></div>
    </div>
    <div class="container border-b-2 px-3 space-y-3">
      <h1 class="xl:text-6xl md:text-5xl text-3xl "><span id="flying-time-counter" class="value" tar="100000">0</span>+</h1>
      <p class="text-sm font-normal">Cumulative Flight Time</p>
      <div class=""></div>
    </div>
  </div>
</section>

core/templates/core/tb.html
{% extends 'base.html' %}
{% load static i18n %}
{% load static %}
{% block title %}Thrust Bench | Drone Anatomy{% endblock title %}
{% block body %}

<main>
    <div class="w-full max-w-[1920px] h-[60vh] max-h-[600px] mx-auto flex items-end justify-center" style="background: linear-gradient(13deg, rgba(55,50,51,1) 0%, rgba(115,117,107,0.97) 58%, rgba(202,203,195,1) 100%);">
        <!-- <img
        data-src="{% static 'core/img/tb/tb6_l.jpg' %}"
        alt=""
        class="lazy w-full h-full object-cover object-center"
        /> -->
        <h1 class="lg:text-7xl text-5xl text-white font-semibold my-8">DA-20KGF</h1>
    </div>
    <div class="xl:w-8/12 lg:9/12 max-w-5xl mx-auto my-20 flex flex-col lg:flex-row justify-between gap-12">
        <div class="w-1/3 h-[400px] mx-4 lg:mx-0 overflow-hidden rounded-md shadow-md ">

            <img data-src="{% static 'core/img/tb/tb7.jpg' %}" height="400" width="220" alt="tb" class="lazy hover:scale-105 transition-transform ease-in-out duration-200 w-full h-full object-cover object-center">
        </div>
        <article class="mx-auto px-4 w-2/3">
            <h2 class="text-2xl my-2 font-semibold">DA-20KGF Thrust Bench</h2>
            <p class="text-justify text-black">
                DA-20KGF motor and propeller test stand is designed to test motors and propellers of medium UAV. It allows you to finish drone torque measuring of 20kg thrust for max 40'' propeller. The test stand will help you to figure out the most efficient drone propulsion system and extend the flight time.
                <br>
                The thrust tester is capable of testing the thrust, torque, voltage, current, RPM, motor and propeller efficiency of your drone propulsion system.
            </p>
            <h3 class="text-xl font-medium mt-4 mb-4">Specification of DA-20KGF Drone Torque Measuring</h3>
            <div class="flex lg:gap-16 gap-8">
                <ul class="space-y-2">
                    <li class="text-gray-500">Suggested Propulsion System</li>
                    <li class="text-gray-500">Max Thrust</li>
                    <li class="text-gray-500">Max Propeller</li>
                    <li class="text-gray-500">Current</li>
                    <li class="text-gray-500">RPM</li>
                    <li class="text-gray-500">Temperature</li>
                </ul>        
                
                <ul class="space-y-2">
                    <li class="text-gray-500">Max Thrust > 3kg</li>
                    <li class="text-gray-500">20kg</li>
                    <li class="text-gray-500">40inch</li>
                    <li class="text-gray-500">0-150A</li>
                    <li class="text-gray-500">30-15000RPM</li>
                    <li class="text-gray-500">0-100°C</li>
                </ul>
            </div>
        </article>
    </div>

    <section class="w-full bg-zinc-50 text-center py-8">
        <h2 class="my-8 lg:text-5xl text-3xl font-semibold">DA ThrustBench Console</h2>
        <h3 class="text-lg">DA ThrustBench console software allows you to monitor the key data and display the data in diagrams.</h3>
    
        <div class="lg:w-[70vw] max-w-5xl h-fit mx-auto my-12">
            <img data-src="{% static 'core/img/tb/tb_console.png' %}" alt="tb console" class="lazy w-full h-full object-cover object-center">
        </div>
    </section>
    <section
        id=""
        class="w-full py-32 flex flex-col gap-10 justify-center items-center bg-[#fdf9e8]"
    >
        <h3
        class="lg:text-5xl text-3xl text-center"
        data-aos="fade-up"
        data-aos-duration="500"
        >
        Contact To Learn More
        </h3>
        <div class="" data-aos="slide-up" data-aos-duration="400">
        <a
            href="{% url 'core:whatsapp-redirect' %}" target="_blank"
            class="bg-yellow-500 text-white px-4 py-2 xl:text-2xl text-lg font-medium hover:bg-transparent hover:border-2 border-yellow-500 hover:text-black hover:scale-110 transition-all duration-300 linear"
            >Contact Us</a
        >
        </div>
    </section>
</main>
{% endblock body %}

core/templates/core/uav-data-processing.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Solutions | Drone Anatomy
{% endblock title %}

{% block body %}

<main class="">
    <div class="relative h-dvh flex items-center solution-banner-container">
        
        
        <div class="w-10/12 flex justify-between mx-auto z-[1]">
            <div class="">

                <h1 class="shadow-text xl:text-5xl py-4 text-3xl font-semibold leading-[1.4] text-white" data-aos="fade-up" data-aos-duration="400">UAV Data Processing</h1>
                <p class="shadow-text text-white" data-aos="fade-up" data-aos-delay="200">Decode the vault of high-quality UAV Data through our Aerial Data Processing solutions, and craft your vision into reality.</p>
            </div>
            <div class="flex flex-col gap-4">
                <a href="{% url 'core:contact' %}" class="btn">Talk to our team</a>
                <a href="{% url 'core:whatsapp-redirect' %}" class="bg-white px-4 max-h-20 py-2 text-center border-yellow-500 hover:bg-transparent hover:text-white hover:border">Enquire on whatsapp</a>
            </div>
        </div>
    </div>
    <div class="w-11/12 lg:w-9/12 mx-auto flex flex-col gap-10">

        <div class="my-8">
            <h2 class="text-3xl my-8 font-medium">Deliverables We Offer</h2>
            <div class="grid lg:grid-cols-3 lg:gap-8 gap-4 justify-between">
                <div class="flex flex-col p-4 gap-4 shadow-lg bg-accentLight" data-aos="zoom-in">
                    <h3 class="font-medium text-xl">Orthomosaic Maps</h3>
                    <p class="text-justify">Drone images are corrected for image distortion and stitched together during post-processing to create a highly-accurate orthomosaic map. Each pixel contains 2D geo-information (X, Y) and can directly procure accurate measurements, such as horizontal distances and surfaces.</p>
                </div>
                <div class="flex flex-col p-4 gap-4 shadow-lg bg-accentLight" data-aos="zoom-in">
                    <h3 class="font-medium text-xl">3D Point Cloud</h3>
                    <p class="text-justify">A densified point cloud can be generated from drone images. Each point contains geospatial (X, Y, Z) and color information. It provides a very accurate model for distance (slant and horizontal), area and volume measurements.</p>
                </div>
                <div class="flex flex-col p-4 gap-4 shadow-lg bg-accentLight" data-aos="zoom-in">
                    <h3 class="font-medium text-xl">3D textured mesh</h3>
                    <p class="text-justify">The 3D textured mesh replicates the edges, faces, vertices, and textures of the area captured by the drone. This model is particularly beneficial for visual inspections and becomes especially valuable when external stakeholders or public participation is integral to a project.</p>
                </div>
                <div class="flex flex-col p-4 gap-4 shadow-lg bg-accentLight" data-aos="zoom-in">
                    <h3 class="font-medium text-xl">Digital Surface Models (DSM)</h3>
                    <p class="text-justify">Drone images can also be used to create DSM models of the area. Each pixel contains 2D information (X, Y) and the altitude (Z value) of the highest point for this position.</p>
                </div>
                <div class="flex flex-col p-4 gap-4 shadow-lg bg-accentLight" data-aos="zoom-in"> 
                    <h3 class="font-medium text-xl">Digital Terrain Models (DTM)</h3>
                    <p class="text-justify">After filtering objects such as buildings, the drone images can be used to create DTMs with each pixel containing 2.5D information (X, Y, and Z value of the highest altitude).</p>
                </div>
                <div class="flex flex-col p-4 gap-4 shadow-lg bg-accentLight" data-aos="zoom-in">
                    <h3 class="font-medium text-xl">Contour Maps</h3>
                    <p class="text-justify">Depending on the project requirements, either the DTM or DSM model, with custom contour intervals, can be used to create a contour lines map, giving you a better understanding of the surface of the area shot by the drone.</p>
                </div>
                
            </div>
        </div>
    </div>

    <div class="w-full flex h-[30vh] flex-col gap-10 justify-center items-center bg-[#fdf9e8]">
        <h3 class="lg:text-3xl text-xl text-center" data-aos="fade-up" data-aos-duration="500">Talk to our team for any queries regarding drone surveying for your Industry.</h3>
        <!-- <h4>Talk to our team for any queries regarding drone surveying for your Industry.</h4> -->
        <a href="{% url 'core:contact' %}" class=" bg-yellow-500 text-white px-4 py-2 3xl:text-2xl text-lg font-medium  hover:bg-transparent hover:border-2 border-yellow-500 hover:text-black hover:scale-105 transition-all duration-300 ease-linear">Get in touch with us</a>
    </div>
</main>

{% endblock body %}

{% block javascript %}
<script>
    document.addEventListener('DOMContentLoaded', function () {
        new Splide('#image-slider', {
            type       : 'fade',
            autoplay   : true,
            interval   : 3000,
            pauseOnHover: false,
            pagination : false,
            arrows     : false,
        }).mount();
    });
</script>
{% endblock javascript %}

core/templates/core/upcoming.html
{% extends 'base.html' %} 
{% load static %} 
{% block css %}
<style>
    .upcomingBanner {

        background: #0F2027;  /* fallback for old browsers */
        background: -webkit-linear-gradient(to bottom, #2C5364, #203A43, #0F2027);  /* Chrome 10-25, Safari 5.1-6 */
        background: linear-gradient(to bottom, #2C5364, #203A43, #0F2027); /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    }
</style>
{% endblock css %}
{% block body %}
<main class="flex-1">
  <div class="upcomingBanner flex flex-col items-center justify-center gap-4 mt-24 w-full h-[30vh] bg-black text-white text-center">
    <h1 class="text-2xl lg:text-5xl 3xl:text-5xl font-semibold">Discover Our Upcoming Products</h1>
    <p>
      Discover our innovative products coming soon. Be the first to experience
      the future of technology and sustainability.
    </p>
  </div>
  <div class="py-4">
      <h2 class="text-5xl font-semibold text-center leading-[1.5] mt-8">Coming Soon</h2>
    
    <div class="upcoming-products-list md:grid md:grid-cols-2 justify-between gap-4 w-10/12 mx-auto mt-8">
        <div class="upcoming-product-card w-full border-2 p-4 flex flex-col shadow-md my-8 bg-gray-100">
            <h3 class="text-5xl font-medium">Mini Drone</h3>
            <p class="text-black">Lorem ipsum dolor sit amet consectetur adipisicing elit. </p>
            <div class="overflow-hidden w-full aspect-[16/9] my-8 rounded">
                <img data-src="{% static 'core/img/p10.png' %}" alt="mini drone image" class="lazy h-full w-full object-contain" >
            </div>
            <div class="flex justify-between items-center">
                <a href="#" class="cta-accent bg-black px-3 py-1 items-center justify-center text-white text-sm sm:text-lg transition-all duration-400 ease-in-out hover:bg-yellow-400 hover:text-black flex">Learn More</a>
                <p>12/1/2025</p>
            </div>
        </div>
        <div class="upcoming-product-card w-full border-2 rounded p-4 flex flex-col shadow-md my-8">
            <h3 class="text-3xl font-semibold">Mini Drone</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit.</p>
            <div class="overflow-hidden w-full aspect-[16/9] bg-slate-300 my-8 rounded">
                <img data-src="{% static 'core/img/p16.png' %}" alt="mini drone image" class="lazy h-full w-full object-contain object-center">
            </div>
            <div class="flex justify-between items-center">
                <a href="#" class="cta-accent bg-yellow-500 px-4 py-2 items-center justify-center text-white text-sm sm:text-lg transition-all duration-400 ease-in-out hover:bg-yellow-400 hover:text-black flex">Learn More</a>
                <p>12/1/2025</p>
            </div>
        </div>
        <div class="upcoming-product-card w-full border-2 rounded p-4 flex flex-col shadow-md my-8">
            <h3 class="text-3xl font-semibold">Mini Drone</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam culpa itaque dicta ipsam suscipit, qui voluptates accusamus molestias aperiam libero!</p>
            <div class="overflow-hidden w-full aspect-[16/9] bg-slate-300 my-8 rounded">
                <img src="" alt="mini drone image" class="h-full w-full object-cover">
            </div>
            <div class="flex justify-between items-center">
                <a href="#" class="cta-accent bg-yellow-500 px-4 py-2 items-center justify-center text-white text-sm sm:text-lg transition-all duration-400 ease-in-out hover:bg-yellow-400 hover:text-black flex">Learn More</a>
                <p>12/1/2025</p>
            </div>
        </div>
        <div class="upcoming-product-card w-full border-2 rounded p-4 flex flex-col shadow-md my-8">
            <h3 class="text-3xl font-semibold">Mini Drone</h3>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Aliquam culpa itaque dicta ipsam suscipit, qui voluptates accusamus molestias aperiam libero!</p>
            <div class="overflow-hidden w-full aspect-[16/9] bg-slate-300 my-8 rounded">
                <img src="" alt="mini drone image" class="h-full w-full object-cover">
            </div>
            <div class="flex justify-between items-center">
                <a href="#" class="cta-accent bg-yellow-500 px-4 py-2 items-center justify-center text-white text-sm sm:text-lg transition-all duration-400 ease-in-out hover:bg-yellow-400 hover:text-black flex">Learn More</a>
                <p>12/1/2025</p>
            </div>
        </div>

    </div>
    
  </div>

  <!-- <div class="">
    <h1>Stay Updated</h1>
    <p>Be the first to know about our product launches and exclusive offers.</p>
    <form action="">
        input
    </form>
  </div> -->
</main>
{% endblock body %}