blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.BlogListView.as_view(), name='bloglist'),
    path('<int:pk>/', views.BlogDetailView.as_view(), name='blogdetail'),
    # path('upload_image/', views.upload_image, name='upload_image'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("core.urls")),
    path('tinymce/', include('tinymce.urls')),
    path('blogs/', include("blog.urls")),
    path('shop/', include("shop.urls")),
    path('gallery/', include("gallery.urls")),
    path('training/', include("training.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views

app_name = 'core'


urlpatterns = [
    path('', views.index_view, name='home'),
    path('agri-drone', views.agri_view, name='agri-detail'),
    path('about', views.about_view, name='about'),
    path('contact', views.contact_view, name='contact'),
    path('career', views.career_view, name='career'),
    path('mapping', views.mapping_view, name='mapping'),
    path('thrustbench', views.tb_view, name='tb'),
    path('uav-data-processing', views.uav_data_processing_view, name='uav-data-processing'),
    path('subscribe', views.subscribe_newsletter, name='subscribe_newsletter'),
    path('whatsapp-redirect', views.whatsapp_redirect, name='whatsapp-redirect'),
    path('lang-select', views.set_language, name='set-language'),
    path('upcoming', views.upcoming_view, name='upcoming-page'),
]

training/urls.py
from django.urls import path
from . import views

app_name = 'training'

urlpatterns = [
    path('', views.training_view, name='training'),
]

core/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField(
        label='Name',
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Your Name'})
        
    )
    email = forms.EmailField(
        label='Email',
        max_length=200,
        widget=forms.TextInput(attrs={'placeholder': 'Your Email'})
    )
    message = forms.CharField(
        label='Message',
        widget=forms.Textarea(attrs={'placeholder': 'Your Message'})
    )


class SubscriberForm(forms.Form):
    email = forms.EmailField()


class CareerForm(forms.Form):
    name = forms.CharField(
        label='Name',
        required=True,
        max_length=100,
        widget=forms.TextInput(attrs={'placeholder': 'Enter Your Name...'})
        
    )
    email = forms.EmailField(
        label='Email',
        required=True,
        max_length=200,
        widget=forms.TextInput(attrs={'placeholder': 'Enter Your Email...'})
    )
    position = forms.CharField(
        label='Position', 
        required=True,
        widget=forms.TextInput(attrs={'placeholder': 'Applying For Position...'})
    )
    message = forms.CharField(
        label='Message',
        widget=forms.Textarea(attrs={'placeholder': 'Your Message'})
    )
    resume = forms.FileField(
        required=True,
        label='Resume',
        # widget=forms.ClearableFileInput(attrs={'multiple': False})
        )
    
    def clean_resume(self):
        resume = self.cleaned_data.get('resume')
        if resume:
            if not resume.name.endswith('.pdf'):
                raise forms.ValidationError("Only PDF files are allowed.")
            if resume.size > 2 * 1024 * 1024:  # 2 MB limit
                raise forms.ValidationError("The file size should not exceed 2 MB.")
        return resume

templates/components/header.html
{% load static i18n %}
{% load static %}

<header
  id="header"
  class="fixed top-0 z-10 w-full text-black flex-col items-center border-b-transparentgray drop-shadow-lg bg-transparent saturate-100 transition-all duration-300 linear"
>
  <div id="logo-container"
    class="container mx-auto h-full flex items-center justify-between w-10/12"
  >
    <a id="logoanchor" href="{% url 'core:home' %}" class="h-[64px] xl:h-[72px] 3xl:h-[92px] transition-all duration-400 ease-linear overflow-hidden">
      <div class="logo items-center overflow-hidden flex h-full mt-1">
        <img
          id="logo-light"
          src="{% static 'core/img/da-logo-wht-outline1.png' %}"
          alt="drone anatomy"
          class="preload object-cover h-full"
          width="128"
          height="72"
        />
        
        <img
          id="logo-dark"
          src="{% static 'core/img/da-logo-blk-outline.png' %}"
          alt="drone anatomy"
          class="hidden object-cover h-full"
          width="128"
          height="72"
        />
      </div>
    </a>
    <nav class="navbar hidden xl:flex h-full">
      <ul class="navlinks flex gap-6 h-[64px] xl:h-[72px] 3xl:h-[92px] flex-nowrap text-nowrap items-center">
        <li id="product-link" class="h-full flex items-center">
            
          <a
            href="#"
            class="nav-links transition-colors group duration-150 ease-in-out hover:text-yellow-400"
            >{% trans "PRODUCTS" %}</a
          >
          <div
            id="product-dropdown"
            class="h-0 hidden w-fit absolute justify-between bg-white rounded text-black transition-transform duration-500 ease-linear hover:flex"
            style="top: 72px;"
            >
            <ul>
                <li class="px-6 py-2 text-lg hover:text-yellow-500"><a href="{% url 'core:agri-detail' %}">Agriculture Drones</a></li>
                <li class="border-t border-gray-400 px-6 py-2 text-lg hover:text-yellow-500"><a href="{% url 'core:tb' %}">Thrust Bench</a></li>
                <li class="border-t border-gray-400 px-6 py-2 text-lg hover:text-yellow-500"><a href="{% url 'core:agri-detail' %}">Flight Controller</a></li>
            </ul>
            </div>
        </li>

        <li id="industry-link" class="h-full flex items-center">
            
            <a
              href="#"
              class="nav-links transition-colors group duration-150 ease-in-out hover:text-yellow-400"
              >{% trans "SOLUTIONS" %}</a
            >
            <div
              id="industry-dropdown"
              class="h-0 hidden w-fit absolute justify-between bg-white rounded text-black transition-transform duration-500 ease-linear hover:flex"
              style="top: 72px;"
              >
              <ul>
                <li class="px-6 py-2 text-lg hover:text-yellow-500"><a href="{% url 'core:mapping' %}">Mapping & Surveying</a></li>
                <li class="border-t border-gray-400 px-6 py-2 text-lg hover:text-yellow-500"><a href="{% url 'core:uav-data-processing' %}">UAV Data Processing</a></li>
                
            </ul>
              </div>
          </li>

        <li>
          <a
            href="{% url 'training:training' %}"
            class="nav-links transition-colors duration-150 ease-in-out hover:text-yellow-400"
            >{% trans "TRAINING" %}</a
          >
        </li>
        <li>
          <a
            href="{% url 'core:career' %}"
            class="nav-links transition-colors duration-150 ease-in-out hover:text-yellow-400"
            >{% trans "CAREER" %}</a
          >
        </li>
        <li>
            <a
              href="{% url 'blog:bloglist' %}"
              class="nav-links transition-colors duration-150 ease-in-out hover:text-yellow-400"
              >{% trans "BLOGS" %}</a
            >
          </li>
        <li>
          <a
            href="{% url 'core:about' %}"
            class="nav-links transition-colors duration-150 ease-in-out hover:text-yellow-400"
            >{% trans "ABOUT" %}</a
          >
        </li>
        <li>
          <a
            href="https://main.d2losjnb6rzshe.amplifyapp.com/"
            class="nav-links transition-colors duration-150 ease-in-out hover:text-yellow-400"
            >SHOP</a
          >
        </li>
      </ul>
    </nav>
    <div class="cta space-x-4 flex flex-nowrap text-nowrap">
      <button
        id="cta-light"
        class="hidden border border-black bg-transparent px-4 leading-7 text-black transition-colors duration-300 ease-in-out hover:bg-white hover:border-none hover:text-black xl:inline"
      >
        {% trans "Watch a Demo" %}
      </button>
      <a href="{% url 'core:contact' %}"
      id="cta-white"
        class="cta-accent hidden hover:bg-yellow-500 font-medium px-4 leading-8 text-black transition-colors duration-300 ease-in-out hover:text-white xl:inline"
      >
        {% trans "Contact Us" %}
    </a>

      <form action="{% url 'core:set-language' %}" method="get" class="bg-transparent group flex items-center">
            <img data-src="{% static 'core/icons/icons-globe.png' %}" alt="" class="lazy object-cover object-center h-4 w-4 peer">
            <div class="lang-select">
                <select id="lang-select" name="language" onchange="this.form.submit()" class="bg-transparent text-black border-none underline underline-offset-4 pl-2 pr-1 py-1 hover:cursor-pointer group-hover:text-yellow-500 transition-colors duration-300 ease-linear focus:border-none">
                    <option value="en" {% if LANGUAGE_CODE == 'en' %}selected{% endif %} class="bg-white text-black">EN</option>
                    <option value="hi" {% if LANGUAGE_CODE == 'hi' %}selected{% endif %} class="bg-white text-black">हिन्दी</option>
                </select>
            </div>
    </form>
    
      
    <button id="mobile-menu-btn" class="">
        <img
          id="closed-menu-icon"
          data-src="{% static 'core/img/menu-closed.png' %}"
          alt=""
          class="lazy h-8 lg:h-10 xl:hidden"
        />
        <img
          id="open-menu-icon"
          data-src="{% static 'core/img/menu-open.png' %}"
          alt=""
          class="lazy h-8 hidden lg:h-10 xl:hidden"
        />
      </button>
    </div>
  </div>

  <div id="mobile-menu" class="w-full bg-white p-8 text-black hidden xl:hidden">
    <div class="w-11/12 mx-auto space-y-7 grid-col justify-center">
      <div class="cta flex w-full justify-center space-x-3 text-nowrap">
        <button
          class="cta-accent-border border border-yellow-500 bg-transparent px-4 leading-7 text-yellow-500 transition-colors duration-300 ease-in-out hover:bg-yellow-500 hover:text-black"
        >
          {% trans "Watch a Demo" %}
        </button>
        <a href="{% url 'core:contact' %}"
          class="cta-accent bg-yellow-500 px-4 leading-8 text-white transition-colors duration-300 ease-in-out hover:bg-yellow-600"
        >
          {% trans "Contact Us" %}
    </a>
      </div>
      <nav id="mobile-nav" class="">
        <ul class="navlinks space-y-5 flex-col">
          <li id="mobile-product-link-wrapper" class="">
            <a
              href="{% url 'core:agri-detail' %}"
              id="mobile-product-link"
              class="nav-links block transition-colors duration-300 ease-in-out w-full hover:text-yellow-400 peer"
              >{% trans "PRODUCTS" %}</a
            >
          </li>
          <div id="mobile-product-dropdown" class="hidden">
            <ul class="space-y-1">
                <li class="pl-3 text-base text-gray-500 hover:text-yellow-500 focus:text-yellow-500"><a href="{% url 'core:agri-detail' %}">Agriculture Drones</a></li>
                <li class="pl-3 text-base text-gray-500 hover:text-yellow-500 focus:text-yellow-500"><a href="{% url 'core:tb' %}">Thrust Bench</a></li>
                <li class="pl-3 text-base text-gray-500 hover:text-yellow-500 focus:text-yellow-500"><a href="{% url 'core:agri-detail' %}">Flight Controller</a></li>
            </ul>
          </div>
          <li id="mobile-industry-link-wrapper">
            <a
              href="#"
              id="mobile-industry-link"
              class="nav-links block transition-colors duration-300 ease-in-out w-full hover:text-yellow-400"
              >{% trans "SOLUTIONS" %}</a
            >
          </li>
          <div id="mobile-industry-dropdown" class="hidden">
            <ul class="space-y-1">
                <li class="pl-3 text-base text-gray-500 hover:text-yellow-500 focus:text-yellow-500"><a href="{% url 'core:mapping' %}">Mapping and Surveying</a></li>
                <li class="pl-3 text-base text-gray-500 hover:text-yellow-500 focus:text-yellow-500"><a href="{% url 'core:uav-data-processing' %}">UAV Data Processing</a></li>                
            </ul>
          </div>
          

          <li>
            <a
              href="{% url 'training:training' %}"
              class="nav-links transition-colors duration-300 ease-in-out hover:text-yellow-400"
              >{% trans "TRAINING" %}</a
            >
          </li>
          <li>
            <a
              href="{% url 'core:career' %}"
              class="nav-links transition-colors duration-300 ease-in-out hover:text-yellow-400"
              >{% trans "CAREER" %}</a
            >
          </li>
          <li>
            <a
              href="{% url 'blog:bloglist' %}"
              class="nav-links transition-colors duration-300 ease-in-out hover:text-yellow-400"
              >{% trans "BLOGS" %}</a
            >
          </li>
          <li>
            <a
              href="{% url 'core:about' %}"
              class="nav-links transition-colors duration-300 ease-in-out hover:text-yellow-400"
              >{% trans "ABOUT" %}</a
            >
          </li>
        </ul>
      </nav>
    </div>
  </div>
    
    
</header>